server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: file-storing
          uri: http://file-storing:8081
          predicates:
            - Path=/files/**
        - id: file-analysis
          uri: http://file-analysis:8082
          predicates:
            - Path=/analysis/**
