server:
  port: 8082

spring:
  application:
    name: file-analysis-service

  datasource:
    url: jdbc:h2:mem:analysisdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
